export const usoCFDI = [
  { "raw": "CN01", "verbose": "Nómina" },
  { "raw": "CP01", "verbose": "Pagos" },
  { "raw": "D01", "verbose": "Honorarios Médicos dentales y gastos hospitalarios" },
  { "raw": "D02", "verbose": "Gastos Médicos por incapacidad o discapacidad" },
  { "raw": "D03", "verbose": "Gastos Funerales" },
  { "raw": "D04", "verbose": "Donativos" },
  { "raw": "D05", "verbose": "Intereses reales efectivamente pagados por créditos Hipotecarios de casa habitación" },
  { "raw": "D06", "verbose": "Aportaciones voluntarias al SAR" },
  { "raw": "D07", "verbose": "Primas por seguros de gastos Médicos" },
  { "raw": "D08", "verbose": "Gastos de transportación escolar obligatoria" },
  { "raw": "D09", "verbose": "Depósitos en cuentas para el ahorro" },
  { "raw": "D10", "verbose": "Pago por sevicios de colegiaturas" },
  { "raw": "G01", "verbose": "Adquisición de Mercancías" },
  { "raw": "G02", "verbose": "Devoluciones, Descuentos o Bonificaciones" },
  { "raw": "G03", "verbose": "Gastos en general" },
  { "raw": "I01", "verbose": "Construcciones" },
  { "raw": "I02", "verbose": "Mobiliario y equipo de oficina" },
  { "raw": "I03", "verbose": "Equipos de transporte" },
  { "raw": "I04", "verbose": "Equpo de computo y accesorios" },
  { "raw": "I05", "verbose": "Dados, troqueles, moldes, matrices y herramientas" },
  { "raw": "I06", "verbose": "Comunicationes telefónicas" },
  { "raw": "I07", "verbose": "Comunicaciones satelitales" },
  { "raw": "I08", "verbose": "Otra Maquinaria y Equipo" },
  { "raw": "P01", "verbose": "Por definir" },
  { "raw": "S01", "verbose": "Sin efectos fiscales" }
]

export const regimenFiscal = [
  { "raw": "601", "verbose": "Personas morales" },
  { "raw": "603", "verbose": "Peronas morales con fines no lucrativos" },
  { "raw": "605", "verbose": "Sueldos y Salarios e ingresos asimilados a salarios" },
  { "raw": "606", "verbose": "Arendamiento" },
  { "raw": "607", "verbose": "Régimen de enajenación o adquisiciones de bienes" },
  { "raw": "608", "verbose": "Demas ingresos" },
  { "raw": "609", "verbose": "Consolidación" },
  { "raw": "610", "verbose": "Residentes extranjeros" },
  { "raw": "611", "verbose": "Ingresos por dividendos" },
  { "raw": "612", "verbose": "Peronas físicas con actividad empresarial" },
  { "raw": "614", "verbose": "Ingresos por interes" },
  { "raw": "615", "verbose": "Ingresos por obtención de premios" },
  { "raw": "616", "verbose": "Sin obligaciones fiscales" },
  { "raw": "620", "verbose": "Sociedades cooperativos de producción que optan por diferir sus ingresos" },
  { "raw": "621", "verbose": "Régimen de incorporación fiscal" },
  { "raw": "622", "verbose": "Actividades agrícolas, ganaderas, silvícolas y pesqueras" },
  { "raw": "623", "verbose": "Opcional para grupos de sociedades" },
  { "raw": "624", "verbose": "Coordinados" },
  { "raw": "625", "verbose": "Plataformas digitales" },
  { "raw": "626", "verbose": "Régimen simplificado de confianza" },
  { "raw": "628", "verbose": "Hidrocarburos" },
  { "raw": "629", "verbose": "Régimen fiscal preferente, empresas multinacionales" },
  { "raw": "630", "verbose": "Enajenacón de acciones en bolsa de valores" }
]

export const formaPago = [
  { "raw": "01", "verbose": "Efectivo" },
  { "raw": "03", "verbose": "Transferencia electrónica" },
  { "raw": "04", "verbose": "Tarjeta de crédito" },
  { "raw": "05", "verbose": "Mondero electrónico" },
  { "raw": "06", "verbose": "Dinero electrónico" },
  { "raw": "07", "verbose": "Tarjetas digitales" },
  { "raw": "08", "verbose": "Vales de despensa" },
  { "raw": "28", "verbose": "Tarjeta de debito" },
]