# Generated by Django 5.1.1 on 2024-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(verbose_name='RFC')),
                ('name', models.CharField(verbose_name='Nombre del emisor')),
                ('zip', models.IntegerField(verbose_name='Postal Code')),
                ('certificate', models.FileField(upload_to='', verbose_name='This is the CSD certificate for singing the invoices')),
                ('certificate_key', models.FileField(upload_to='', verbose_name='This is the CSD key for singing the invoices')),
                ('password', models.CharField(verbose_name='Certificate password')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('folio', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('url_sign', models.CharField(verbose_name='URL used to sign invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Saleor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleor_api', models.CharField(verbose_name='Saleor API URL')),
                ('username', models.CharField(verbose_name='Saleor user name')),
                ('password', models.CharField(verbose_name='Saleor password')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('rfc', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
