# Generated by Django 5.1.1 on 2024-10-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_pdf',
            field=models.FileField(default='', upload_to='', verbose_name='This is the PDF invoice'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_xml',
            field=models.FileField(default='', upload_to='', verbose_name='This is the xml invoice'),
        ),
    ]
