# Generated by Django 5.1.1 on 2024-10-07 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0002_invoices_invoice_pdf_invoices_invoice_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
