# Generated by Django 5.1.1 on 2024-10-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0003_alter_invoices_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(default='MASO451221PM4', on_delete=django.db.models.deletion.CASCADE, to='cfdi.users'),
        ),
    ]
