# Generated by Django 5.1.1 on 2024-10-15 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0004_invoices_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('server', models.CharField(verbose_name='Server name')),
                ('port', models.IntegerField(verbose_name='Port number')),
            ],
        ),
        migrations.AlterField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfdi.users'),
        ),
    ]
