# Generated by Django 5.1.1 on 2024-10-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0005_smtp_alter_invoices_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
